#/tmp/data1 auto created. we may need to connect host and apply chcon -Rv -t container_file_t /tmp/data1
#before this connect to host oc debug node/master01 and chrot /host
kind: PersistentVolume
apiVersion: v1
metadata:
  name: web-hostpath
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  reclaimPolicy:
    - Delete
  hostPath:
    path: "/tmp/data1"

