apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  name: db
  namespace: sandbox
 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
 

