apiVersion: apps/v1
kind: Deployment
metadata:
 
  labels:
    app: todoapp
  name: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  strategy: {}
  template:
    metadata:
     
      labels:
        app: todoapp
    spec:
      containers:
      - env:
        - name: USERNAME
          value: taskuser
        - name: PASSWORD
          value: taskpass
        - name: DBNAME
          value: TASKDB
        image: quay.io/selcukkaraca/todoapp:v1.0
        name: todoapp
        resources: {}

