apiVersion: v1
data:
  MYSQL_DATABASE: VEFTS0RC
  MYSQL_PASSWORD: dGFza3Bhc3M=
  MYSQL_ROOT_PASSWORD: YWJyYWthZGFicmE=
  MYSQL_USER: dGFza3VzZXI=
kind: Secret
metadata:
  name: secret-todoapp-db
type: Opaque
