apiVersion: apps/v1
kind: Deployment
metadata:
 
  labels:
    app: taskdb
  name: taskdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskdb
  strategy: {}
  template:
    metadata:
      
      labels:
        app: taskdb
    spec:
      
      containers:
      - env:
        - name: MYSQL_USER
          value: taskuser
        - name: MYSQL_PASSWORD
          value: taskpass
        - name: MYSQL_DATABASE
          value: TASKDB
        - name: MYSQL_ROOT_PASSWORD
          value: abrakadabra
        image: quay.io/selcukkaraca/mariadb-105:v1
        name: mariadb-105
       
        resources: {}

